import pic1 from '../../assets/women.jpg'
import pic2 from '../../assets/women1.jpg'
import pic3 from '../../assets/women2.jpg'


export default [
    {
        id: 1,
        img: pic1,
        link: '',
        outofstock: '',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',
    },
    {
        id: 2,
        img: pic2,
        link: '',
        outofstock: '',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',       
    },
    {
        id: 3,
        img: pic2,
        link: '',
        outofstock: '',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',       
    },
    {
        id: 4,
        img: pic1,
        link: '',
        outofstock: '',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',       
    },
    {
        id: 5,
        img: pic2,
        link: '',
        outofstock: '',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',       
    },
    {
        id: 6,
        img: pic3,
        link: '',
        outofstock: '',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',       
    },
    {
        id: 7,
        img: pic2,
        link: '',
        outofstock: '',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',       
    },
    {
        id: 8,
        img: pic3,
        link: '',
        outofstock: 'Out of stock',
        heading: 'Apparel',
        subheading: 'Crop Hoodies are cute, no?',
        price: 'Rs 999',
        originalPrice: 'Rs 1299',
    }
]