/* eslint-disable import/no-anonymous-default-export */
import pic2 from "./assets/black.jpg"
import pic5 from "./assets/jwellery.jpg"
import pic6 from "./assets/pant.jpg"
import pic4 from "./assets/purple.jpg"
import pic1 from "./assets/red.jpg"
import pic3 from "./assets/yellow.jpg"

export default [
    {
        id: 1,
        img: pic1,
        outofstock: "",
        heading: "Hoodie",
        subheading: "Crop Hoodies are cute, no?",
        price: 999,
        originalPrice: 1299,
        category: "Tops and Tees",
        color: "red",
        rating: 4,
    },
    {
        id: 2,
        img: pic2,
        outofstock: "",
        heading: "Hoodie",
        subheading: "Crop Hoodies are cute, no?",
        price: 2999,
        originalPrice: 3299,
        category: "Tops and Tees",
        color: "black",
        rating: 5,
    },
    {
        id: 3,
        img: pic3,
        outofstock: "",
        heading: "Hoodie",
        subheading: "Crop Hoodies are cute, no?",
        price: 2199,
        originalPrice: 2699,
        category: "Tops and Tees",
        color: "yellow",
        rating: 2,
    },
    {
        id: 4,
        img: pic4,
        outofstock: "",
        heading: "Hoodie",
        subheading: "Crop Hoodies are cute, no?",
        price: 1499,
        originalPrice: 2399,
        category: "Tops and Tees",
        color: "blue",
        rating: 3,
    },
    {
        id: 5,
        img: pic3,
        outofstock: "",
        heading: "Hoodie",
        subheading: "Crop Hoodies are cute, no?",
        price: 1999,
        originalPrice: 2699,
        category: "Tops and Tees",
        color: "yellow",
        rating: 1,
    },
    {
        id: 6,
        img: pic6,
        outofstock: "",
        heading: "Trouser",
        subheading: " Lorem ipsum dolor sit, ecessitati",
        price: 2299,
        originalPrice: 3799,
        category: "Jeans and Trousers",
        color: "blue",
        rating: 4,
    },
    {
        id: 7,
        img: pic5,
        outofstock: "",
        heading: "Jwellery",
        subheading: "Neck chain for jwellery category",
        price: 999,
        originalPrice: 1299,
        category: "Jewellery",
        color: "silver",
        rating: 5,
    },
    {
        id: 8,
        img: pic3,
        outofstock: "Out of stock",
        heading: "Hoodie",
        subheading: "Lorem ipsum dolor sit, ecessitati",
        price: 1699,
        originalPrice: 2299,
        category: "Tops and Tees",
        color: "yellow",
        rating: 3,
    },
]
